INFO     root:entity.py:43 Unable to find a row with primary key 531aadaa-9462-45ed-87bd-652c7098b21e, in Collection table.