INFO     root:entity.py:43 Unable to find a row with primary key 372350db-231a-40aa-9f69-522a81913ed5, in Geneset table.