INFO     root:entity.py:43 Unable to find a row with primary key 06a0b14c-9fab-44ca-a28d-c017ee2692bc, in Collection table.