INFO     root:entity.py:43 Unable to find a row with primary key 13adb037-f8e1-4134-8a90-9f2269d118cd, in Collection table.