INFO     root:entity.py:43 Unable to find a row with primary key 6cecbf68-64c7-4e4b-9850-da856a5e4d90, in Collection table.